name: Build and deploy Node.js app to Azure Web App - samiTest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact part 1
        uses: actions/upload-artifact@v4
        with:
          name: node-app-part1
          path: |
            ./build/**/*.*
            !./build/static/**/*.*

      - name: Upload artifact part 2
        uses: actions/upload-artifact@v4
        with:
          name: node-app-part2
          path: ./build/static/**/*.*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact part 1
        uses: actions/download-artifact@v4
        with:
          name: node-app-part1
          path: ./build

      - name: Download artifact part 2
        uses: actions/download-artifact@v4
        with:
          name: node-app-part2
          path: ./build/static

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'samiTest'
          slot-name: 'Production'
          package: ./build
