name: Build and deploy Node.js app to Azure Web App - FlutterFlows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Increase file descriptor limit
        run: ulimit -n 4096

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Upload artifact for deployment job (batch 1)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-batch-1
          path: 'part_of_your_project/*'

      - name: Upload artifact for deployment job (batch 2)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-batch-2
          path: 'another_part_of_your_project/*'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job (batch 1)
        uses: actions/download-artifact@v4
        with:
          name: node-app-batch-1

      - name: Download artifact from build job (batch 2)
        uses: actions/download-artifact@v4
        with:
          name: node-app-batch-2
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'FlutterFlows'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_53B354CAA04E4CB2897519E41C33924B }}
